type: '*simpleprometheusreceiver.Config'
doc: |
  Config defines configuration for simple prometheus receiver.
fields:
- name: endpoint
  kind: string
  default: localhost:9090
- name: tls
  type: configtls.TLSClientSetting
  kind: struct
  fields:
  - name: ca_file
    kind: string
    default: ""
  - name: ca_pem
    type: configopaque.String
    kind: string
    default: ""
  - name: cert_file
    kind: string
    default: ""
  - name: cert_pem
    type: configopaque.String
    kind: string
    default: ""
  - name: key_file
    kind: string
    default: ""
  - name: key_pem
    type: configopaque.String
    kind: string
    default: ""
  - name: min_version
    kind: string
    default: ""
  - name: max_version
    kind: string
    default: ""
  - name: reload_interval
    type: time.Duration
    kind: int64
  - name: insecure
    kind: bool
    default: true
  - name: insecure_skip_verify
    kind: bool
    default: false
  - name: server_name_override
    kind: string
    default: ""
- name: read_buffer_size
  kind: int
- name: write_buffer_size
  kind: int
- name: timeout
  type: time.Duration
  kind: int64
- name: headers
  type: map[string]configopaque.String
  kind: map
- name: customroundtripper
  type: func(http.RoundTripper) (http.RoundTripper, error)
  kind: func
- name: auth
  type: '*configauth.Authentication'
  kind: ptr
  fields:
  - name: authenticator
    type: component.ID
    kind: struct
- name: compression
  type: configcompression.CompressionType
  kind: string
  default: ""
- name: max_idle_conns
  type: '*int'
  kind: ptr
- name: max_idle_conns_per_host
  type: '*int'
  kind: ptr
- name: max_conns_per_host
  type: '*int'
  kind: ptr
- name: idle_conn_timeout
  type: '*time.Duration'
  kind: ptr
- name: collection_interval
  type: time.Duration
  kind: int64
  default: 10s
  doc: |
    CollectionInterval is the interval at which metrics should be collected
- name: metrics_path
  kind: string
  default: /metrics
  doc: |
    MetricsPath the path to the metrics endpoint.
- name: params
  type: url.Values
  kind: map
  doc: |
    Params the parameters to the metrics endpoint.
- name: labels
  type: map[string]string
  kind: map
  doc: |
    Labels static labels
- name: use_service_account
  kind: bool
  default: false
  doc: |
    Whether or not to use pod service account to authenticate.
