type: '*googlemanagedprometheusexporter.Config'
doc: |
  Config defines configuration for Google Cloud Managed Service for Prometheus exporter.
fields:
- name: project
  kind: string
  default: ""
- name: user_agent
  kind: string
  default: ""
- name: metric
  type: googlemanagedprometheusexporter.MetricConfig
  kind: struct
  fields:
  - name: prefix
    kind: string
    default: ""
    doc: |
      Prefix configures the prefix of metrics sent to GoogleManagedPrometheus.  Defaults to prometheus.googleapis.com.
      Changing this prefix is not recommended, as it may cause metrics to not be queryable with promql in the Cloud Monitoring UI.
  - name: getclientoptions
    type: func() []option.ClientOption
    kind: func
    doc: |
      GetClientOptions returns additional options to be passed
      to the underlying Google Cloud API client.
      Must be set programmatically (no support via declarative config).
      If GetClientOptions returns any options, the exporter will not add the
      default credentials, as those could conflict with options provided via
      GetClientOptions.
      Optional.
  - name: endpoint
    kind: string
    default: ""
  - name: compression
    kind: string
    default: ""
    doc: |
      Compression specifies the compression format for Metrics and Logging gRPC requests.
      Supported values: gzip.
  - name: use_insecure
    kind: bool
    default: false
    doc: |
      Only has effect if Endpoint is not ""
  - name: grpc_pool_size
    kind: int
    doc: |
      GRPCPoolSize sets the size of the connection pool in the GCP client
- name: timeout
  type: time.Duration
  kind: int64
  default: 12s
- name: sending_queue
  type: exporterhelper.QueueSettings
  kind: struct
  fields:
  - name: enabled
    kind: bool
    default: true
  - name: num_consumers
    kind: int
    default: 10
  - name: queue_size
    kind: int
    default: 1000
  - name: storage
    type: '*component.ID'
    kind: ptr
- name: retry_on_failure
  type: exporterhelper.RetrySettings
  kind: struct
  fields:
  - name: enabled
    kind: bool
    default: false
  - name: initial_interval
    type: time.Duration
    kind: int64
    default: 5s
  - name: randomization_factor
    kind: float64
  - name: multiplier
    kind: float64
  - name: max_interval
    type: time.Duration
    kind: int64
    default: 30s
  - name: max_elapsed_time
    type: time.Duration
    kind: int64
    default: 5m0s
