name: Sync metadata from contrib

on:
 workflow_dispatch:
 
permissions:
  contents: write
  pull-requests: write

jobs:
  sync_metadata:
    name: Sync metadata
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Checkout new branch
        run: git checkout -b metadata-update-${{ steps.date.outputs.date }}
      - name: Download files from contrib
        run: |
          cd cfgschema
          go run .
      - name: Create pull request
        run: gh pr create -B main -H metadata-update-${{ steps.date.outputs.date }} --title 'Merge metadata-update-${{ steps.date.outputs.date }} into main' --body 'Automatic sync PR to update reference files from contrib'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
